# 3.1 Задача. О движении по различным участкам дороги

## Понятие массива
**Массив** — это пронумерованная последовательность величин одинакового типа, обозначенная одним именем. Каждое из значений, составляющих массив, называется компонентой (или элементом массива). Для обращения к элементу массива используется его индекс.

Для обращения к элементу по индексу 5 используется запись `a[5]`, изменить значение, хранящееся по этому индексу можно с помощью оператора присваивания:
```python
a[5] = 47
```

## Создание массива
В NumPy существует много способов создать массив. Проще всего создать массив из списка. Для этого используется функция `array()`:
```python
import numpy as np

a = np.array([-4, 5, 2])
```
При создании массива из списка можно переопределить тип его элементов, например, из списка состоящего из строк, представляющих собой числа, можно создать массив из целых чисел.
```python
a = np.array(['-4', '5', '2'], dtype=int)
```
Например, введем с клавиатуры строку, состоящей из чисел, разделенных пробелом. А затем создадим массив из них:
```python
line = input("Введите числа через пробел : ")
list_a = line.split()
a = np.array(list_a, dtype=int)
```

In [1]:
import numpy as np

a = np.array([-4.0, '5', 2], dtype=int)
print("a = ", a)
a

a =  [-4  5  2]


array([-4,  5,  2])

## Методы массивов
Модуль numpy предоставляет множество методов работы с массивами. Для обращения к ним после имени массива ставится точка,  потом записывается метод и круглые скобки. Некоторые методы, примененные к массиву с именем `a`.

* `a.sum()` - сумма элементов массива
* `a.prod()` - произведение элементов массива
* `а.mean()` - среднее значение элементов массива
* `a.max()` - максимальное значение из элементов массива
* `a.min()` - минимальное значение из элементов массива

In [2]:
import numpy as np

a = np.array([-4, 5, 2])

print("a = ", a)
print("Сумма = ", a.sum())
print("Произведение = ", a.prod())
print("Среднее = ", a.mean())
print("Максимум = ", a.max())
print("Минимум = ", a.min())

a =  [-4  5  2]
Сумма =  3
Произведение =  -40
Среднее =  1.0
Максимум =  5
Минимум =  -4


## Операции с массивами
Математические операции  - сложение (+), умножение (\*), вычитание (-) , деление(/), остаток от деления(%), целочисленное деление (//) -  применяются непосредственно к массивам. Создается новый массив, который заполняется результатами действия математической операции c соответствующими элементами массива. Массивы при этом должны быть одинакового размера

In [3]:
import numpy as np

a = np.array([-4, 5, 2])
b = np.array([3, 2, 1])

print("a + b =", a + b)
print("a - b =", a - b)
print("a * b =", a * b)
print("a / b =", a / b)
print("a % b =", a % b)
print("a // b =", a // b)

a + b = [-1  7  3]
a - b = [-7  3  1]
a * b = [-12  10   2]
a / b = [-1.33333333  2.5         2.        ]
a % b = [2 1 0]
a // b = [-2  2  2]


In [4]:
# операция массива с числом
print("4 + a =", 4 + a)
print("2 * a =", 2 * a)

4 + a = [0 9 6]
2 * a = [-8 10  4]


## Функции  массивов
Некоторые из них для массива с именем `а`. Перед вызовом функций в программе необходимо указать префикс `np` (имя модуля numpy в текущей программе) и точку.

* `round(a, k)` - округляет значения элементов `a` до `k` знаков после запятой, результат - массив
* `sin(a)` - вычисляет синусы от каждого элемента массива `a`, результат - массив
* `cos(a)` - вычисляет косинусы от каждого элемента массива `a`, результат - массив
* `tan(a)` - вычисляет тангенсы от каждого элемента массива `a`, результат - массив
* `arcos(a)` - вычисляет арккосинусы от каждого элемента массива `a`, результат - массив
* `arcsin(a)` - вычисляет арксинусы от каждого элемента массива `a`, результат - массив
* `arctan(a)` - вычисляет арктангенсы от каждого элемента массива a, результат - массив
* `degrees(a)` - переводит каждый элемент массива  `a` в градусы, результат - массив
* `radians(a)` - переводит каждый элемент массива  `a` в радианы, результат - массив
* `log(a)` - вычисляет натуральный логарифм от каждого элемента массива `a`, результат - массив
* `log10(a)` - вычисляет десятичный логарифм от каждого элемента массива `a`, результат - массив
* `exp(a)` - вычисляет экспоненту от каждого элемента массива `a`, результат - массив
* `sum(a)` - вычисляет сумму элементов массива `a`, результат - число
* `prod(a)` - вычисляет произведение элементов массива `a`, результат - число
* `mean(a)` - вычисляет среднее значение элементов массива `a`, результат - число
* `max(a)` - вычисляет максимальное значение из элементов массива `a`, результат - число
* `min(a)`вычисляет минимальное значение из элементов массива `a`, результат - число
* `abs(a)` - применяет функцию модуль для каждого элемента массива `a`, результат - массив
* `pi` - число пи, размноженное на все элементы массива.
* `sqrt(a)` - вычисляет корень от каждого элемента массива `a`, результат - массив

### Пример
Решим задачу с вычислением численности населения, используя массивы из модуля numpy. Создадим массив с различными годами, а затем посчитаем численность населения Земли в эти года по формуле:

$$
\begin{equation*}
    N(t) = \frac{C}{\tau}\cdot\arctan(\frac{T_1-t}{\tau})
\end{equation*}
$$
где:

$t$ - год, для которого вычисляется численность населения;

$C$ - 172 миллиарда человек·лет;

$T_1$ -  2000 год;

$\tau$ - 45 лет.

In [5]:
import numpy as np

def compute_population(t):
    c = 172
    t_1 = 2000
    tau = 45
    y = c / tau * (np.pi / 2 - np.arctan((t_1-t)/tau))
    return y

t = np.array([1000, 1500, 1800, 1850, 1900, 1950, 1990, 2019, 2030])

print("Годы : ", t)

print("Численность : ", np.round(compute_population(t), 3))

Годы :  [1000 1500 1800 1850 1900 1950 1990 2019 2030]
Численность :  [0.172 0.343 0.846 1.114 1.616 2.801 5.168 7.531 8.251]


## Задача. Step 7
Дорога из пункта **А** в пункт **В** состоит из нескольких участков, известны их длины. Для автомобиля известна средняя скорость его движения на каждом участке. Результаты приведены в таблице:
```
Длина участка, км   15  5 12  2 21 17 21  3 10  5 
Скорость, км/ч      60 30 60 45 50 60 50 40 60 40
```
Определить:

1. расстояние между пунктами А и В;
2. время прохождения каждого участка и общее время в пути;
3. среднюю скорость движения;
4. номера тех участков, при движении по которым затрачено максимальное время;
5. длину и время проезда первых четырех участков;
6. среднюю скорость движения по первым четырем участкам.

In [6]:
import numpy as np

# Сформируем массивы длин участков и скорости автомобиля на них:
path = np.array([15, 5, 12, 2, 21, 17, 21, 3, 10, 5])
speed = np.array([60, 30, 60,45, 50, 60, 50, 40, 60, 40])

# Вычислим длину пути от А до В
len_path = path.sum()
print("Расстояние между пунктами А и В :", len_path)

# or
# len_path = np.sum(path)

# Вычислим время прохождения автомобилем каждого участка
# результат получится в виде массива, каждый элемент массива при выводе округлим до 2-х знаков после запятой:
time = path / speed
print("Время на каждом участке :", np.round(time, 2))

# Вычислим общее время в пути,  при выводе округлим значения:
sum_time = time.sum()
print("Общее время в пути : ", round(sum_time, 2))

# Посчитаем среднюю скорость автомобиля (среднюю путевую скорость):
avg_speed = len_path / sum_time
print("Средняя скорость : ", round(avg_speed, 2))

# Вычислим максимальное время и выведем номера участков дороги, на проезд по которым потрачено больше всего времени:
max_time = time.max()
max_path = np.where(time == max_time)[0]
print("Участки, на проезд по которым потрачено больше всего времени :", max_path)

# Посчитаем длину и время проезда по первым 4-м участкам:
len_path_four = path[:4].sum()
print("Длина первых четырех участков :", len_path_four)
time_four = path[:4] / speed[:4]
sum_time_four = time_four.sum()
print("Время проезда :", round(sum_time_four, 2))

# Вычислим среднюю скорость движения по первым четырем участкам:
avg_speed_four = len_path_four / sum_time_four
print("Средняя скорость движения :", round(avg_speed_four, 2))

Расстояние между пунктами А и В : 111
Время на каждом участке : [0.25 0.17 0.2  0.04 0.42 0.28 0.42 0.08 0.17 0.12]
Общее время в пути :  2.15
Средняя скорость :  51.6
Участки, на проезд по которым потрачено больше всего времени : [4 6]
Длина первых четырех участков : 34
Время проезда : 0.66
Средняя скорость движения : 51.43


## Задача. Step 8
Автомобиль движется из пункта А в пункт В по дороге, состоящей из n участков. Ввести длины участков дороги (в км), задавая их на одной строке через пробел. Ввести скорость движения автомобиля на каждом участке (км/ч), также задавая их на одной строке через пробел. Посчитать длину пути, время в пути и среднюю скорость движения автомобиля (среднюю путевую скорость).

**Входные данные:**

* строка, в которой через пробел перечислены длины всех участков дороги (целые числа);
* строка, в которой через пробел перечислены средние скорости на участках (целые числа).

**Выходные данные:**

* длина пути;
* время в пути;
* средняя скорость.
* Для вывода значений использовать строку формата
```
"S = %3d км, T = %5.2f час, V = %5.2f км/ч" 
```
___

**Sample Input:**
```
14 11 11 19 7 18 9 10 13
42 50 30 43 39 36 53 60 49
```
**Sample Output:**
```
S = 112 км, T =  2.64 час, V = 42.37 км/ч
```

In [7]:
import numpy as np

# line_path  = input()
# line_speed = input()

line_path  = '14 11 11 19 7 18 9 10 13'
line_speed = '42 50 30 43 39 36 53 60 49'

s = np.array(line_path.split(), dtype=int)
v = np.array(line_speed.split(), dtype=int)
t = s / v

print("S = %3d км, T = %5.2f час, V = %5.2f км/ч" % (s.sum(), t.sum(), s.sum() / t.sum()))

S = 112 км, T =  2.64 час, V = 42.37 км/ч


## Методы модуля numpy
### Поиск индексов элементов массива 
Для того чтобы найти индексы элементов в массиве, отвечающие некоторому условию, используется метод `where()`, в качестве аргумента которого задается логическое выражение.

Это выражение может включать:

* знаки отношения – равно(==), не равно(!=), больше(>), больше или равно(>=), меньше(<), меньше или равно(<=);
* имена массивов;
* константы;
* выражения.

Результат выполнения функции – массив модуля `tuple`, чтобы получить список индексов в привычном виде, необходимо обратиться к результату по индексу `0` (`[0]`).

Рассмотрим, как работает функция `where()`.

In [8]:
import numpy as np

a = np.array([5, 5, 2, 6, -1])
b = np.array([2, 7, 2, 3, -1])

print(np.where(a == b)[0])
print(np.where(a > b)[0])

[2 4]
[0 3]


In [9]:
a == b

array([False, False,  True, False,  True])

In [10]:
np.where(a == b)

(array([2, 4], dtype=int64),)

In [11]:
type(np.where(a == b))

tuple

In [12]:
type(np.where(a == b)[0])

numpy.ndarray

Если в логическом выражении используются массивы, то они должны быть одинаковой длины, при этом каждый элемент одного массива сравнивается с элементом с тем же индексом второго массива, если логическое выражение выполняется, то индекс этого элемента включается в итоговый список

In [13]:
a = np.array([5, 5, 2, 6, -1])
b = np.array([2, 7, 2, 3, -1])

print(np.where(a == b)[0])
print(np.where(a > b)[0])

[2 4]
[0 3]


Если в логическом выражении используются константа, то каждый элемент массива сравнивается с этой константой, если логическое выражение выполняется, то индекс этого элемента включается в итоговый список

In [14]:
print(np.where(a < 3)[0])
print(np.where(b > 10)[0])

[2 4]
[]


Если в логическом выражении используются выражения, то их результатом может быть либо число, либо массив, но тогда его длина должна соответствовать длине других массивов, используемых в выражении

In [15]:
print(np.where(a >= b.mean())[0])
print(np.where(a + b >= 8)[0])

[0 1 3]
[1 3]


#### Логические выражения
Также в логическом выражении можно использовать логические операции, которые реализуются с помощью функций:

* ИЛИ – `np.logical_or()`;
* И – `np.logical_and()`;
* НЕ – `np.logical_not()`.

В скобках, через запятую перечисляются логические выражения, которые должны быть соединены соответствующей операцией. Например, логическое выражение 
```
a > 0 И a <= 6
```

In [16]:
a = np.array([5, 5, 2, 6, -1])
b = np.array([2, 7, 2, 3, -1])

In [17]:
np.logical_and(a > 0, a <= 6)

array([ True,  True,  True,  True, False])

In [18]:
np.where(
    np.logical_and(a > 0, a <= 6)
)

(array([0, 1, 2, 3], dtype=int64),)

Допускается использование вложенных функций, описывающих логические операции. Например, логическое выражение  
```
(a > 0 И a < 6) ИЛИ (b < 0 ИЛИ b > 7)
```

In [19]:
np.logical_or(
    np.logical_and(a > 0, a < 6),
    np.logical_or(b < 0, b > 7)
)

array([ True,  True,  True, False,  True])

In [20]:
np.where(
    np.logical_or(
        np.logical_and(a > 0, a < 6),
        np.logical_or(b < 0, b > 7)
    )
)

(array([0, 1, 2, 4], dtype=int64),)

## Срезы и индексы
Для обращения к элементам или группе элементов массива используются индексы и срезы.

**Индекс** - это номер элемента в массиве, нумерация начинается с `0`. Для обращения к элементу с заданным индексом используются квадратные скобки: `a[3]` - элемент массива a с индексом 3.

**Срез** – это часть массива, которую можно выделить по индексам:
```
массив[нижняя_граница : верхняя_граница : шаг]
```
Для выделения среза в квадратных скобках указывается нижняя граница среза, верхняя граница, которая в срез не включается, и шаг, с которым выделяются индексы. Части описания среза могут быть опущены. 

In [21]:
import numpy as np

a = np.array([5, 5, 1, 6, 15, 3, 8, -1])

print("a       :", a, "\n")
print("a[2:6]  :", a[2:6])
print("a[2:]   :", a[2:])
print("a[:6]   :", a[:6])
print("a[1:6:2]:", a[1:6:2])
print("a[1::2] :", a[1::2])
print("a[:6:2] :", a[:6:2])
print("a[::2]  :", a[::2])
print()
print("a[::-1] :", a[::-1])
print("a[-2:]  :", a[-2:])
print("a[-2:6] :", a[-2:6])
print("a[-2:-6] :", a[-2:-6])
print("a[-6:-2] :", a[-6:-2])
print("a[-2:-6;-1]:", a[-2:-6:-1])


a       : [ 5  5  1  6 15  3  8 -1] 

a[2:6]  : [ 1  6 15  3]
a[2:]   : [ 1  6 15  3  8 -1]
a[:6]   : [ 5  5  1  6 15  3]
a[1:6:2]: [5 6 3]
a[1::2] : [ 5  6  3 -1]
a[:6:2] : [ 5  1 15]
a[::2]  : [ 5  1 15  8]

a[::-1] : [-1  8  3 15  6  1  5  5]
a[-2:]  : [ 8 -1]
a[-2:6] : []
a[-2:-6] : []
a[-6:-2] : [ 1  6 15  3]
a[-2:-6;-1]: [ 8  3 15  6]


Срез можно рассматривать как новый массив. Оператор:
```python
b = a[1:3]
```
выделяет элементы из массива `а`, начиная с элемента с индексом `1` и заканчивая элементом с индексом `2`, полученный массив записывается в переменную `b`.

In [22]:
b = a[1:3]
b

array([5, 1])

Срезы позволяют с помощью оператора присваивания изменять значения нескольких элементов массива одновременно. Оператор:
```python
a[1:4] = 0
```
присваивает значение `0` элементам массива `a`, начиная с индекса `1` по индекс `3`.

In [23]:
a[1:4] = 0
a

array([ 5,  0,  0,  0, 15,  3,  8, -1])

## Задача. Step 11
Дан массив, в который занесены расходы человека на проезд в течение года.

Сравнить, в какой период зимний или летний тратится больше денег на проезд. Вывести номера месяцев, в которые расходы были наибольшими.

Для реализации программы используйте шаблон.

*Пояснение*. Поскольку нумерация элементов списка начинается с 0, а номера месяцев в году принято начинать с 1, поэтому в шаблоне при выводе списка с номерами месяцев прибавлена 1.

___

**Sample Input:**

**Sample Output:**
```
Зимой на проезд потрачено больше денег, сумма: 3900 руб.
Самая большая сумма:1450 руб., потрачена в следующих месяцах: [ 4  9 10]
```

Здесь также используется:

* `np.argsort()`

* Для выбора нескольких элементов в квадратных скобках можно передать массив индексов.
```
>>> a[[1, 3, 4]] 
array([11, 13, 14])
```

In [24]:
import calendar
import numpy as np

costs = np.array([1200, 1300, 900, 1450, 1300, 1000, 900, 1000, 1450, 1450, 1300, 1400])

winter = np.array('January February December'.split())
summer = np.array('June July August'.split())
months = np.array([m for m in calendar.month_name])

# найдем индексы месяцев для зимы и лета
sorter_months = np.argsort(months)
winter_ind = sorter_months[np.searchsorted (months, winter, sorter=sorter_months)] - 1
summer_ind = sorter_months[np.searchsorted (months, summer, sorter=sorter_months)] - 1

# посчитать сумму за проезд в зимние месяцы и в летние месяцы
sum_winter = costs[winter_ind].sum()
sum_summer = costs[summer_ind].sum()

if sum_winter > sum_summer:
    print("Зимой на проезд потрачено больше денег, сумма: %4d руб." % sum_winter)
elif sum_winter < sum_summer:
    print("Летом на проезд потрачено больше денег, сумма: %4d руб." % sum_summer)
else:
    print("Зимой и летом на проезд тратится одинаковая, сумма: %4d руб." % sum_winter)

# найти максимальную сумму оплаты за месяц    
max_costs = np.max(costs)# вставить выражение

# найти номера месяцев, в которые тратилась наибольшая сумма
max_month = np.where(costs==max_costs)[0]# вставить выражение

print("Самая большая сумма:%4d руб., потрачена в следующих месяцах:" % max_costs, max_month + 1)

Зимой на проезд потрачено больше денег, сумма: 3900 руб.
Самая большая сумма:1450 руб., потрачена в следующих месяцах: [ 4  9 10]


## Задача. Step 13
Дорога из пункта А в пункт В состоит из нескольких участков, известны их длины. Для автомобиля известна средняя скорость его движения на каждом участке. Автомобиль въехал на дорогу в начале участка **k** и выехал с нее после проезда по участку **p**. Найти сколько километров проехал автомобиль по дороге, время движения и среднюю скорость.

**Входные данные:**

* строка, в которой через пробел перечислены длины всех участков дороги (целые числа);
* строка, в которой через пробел перечислены средние скорости на участках (целые числа);
* номер участка, на котором автомобиль въехал на дорогу (целое число);
* номер участка, после которого выехал (целое число).

**Выходные данные:**

* длина пути с **k** по **p** участок;
* время в пути;
* средняя скорость движения автомобиля.
* Для вывода значений использовать строку формата:
```
"S = %3d км, T = %5.2f час, V = %5.2f км/ч" 
```
___

**Sample Input:**
```
20 8 9 18 5 12 16 16 6 7
44 70 44 66 46 38 38 37 66 67
4
7
```
**Sample Output:**
```
S =  49 км, T =  1.28 час, V = 38.34 км/ч
```

In [25]:
import numpy as np

# line_path  = input()
# line_speed = input()
# k = int(input())
# p = int(input())

line_path  = '14 11 11 19 7 18 9 10 13'
line_speed = '42 50 30 43 39 36 53 60 49'
k = 4
p = 7

s = np.array(line_path.split(), dtype=int)
v = np.array(line_speed.split(), dtype=int)

# slices
s = s[k:p+1]
v = v[k:p+1]
t = s / v

print("S = %3d км, T = %5.2f час, V = %5.2f км/ч" % (s.sum(), t.sum(), s.sum() / t.sum()))

S =  44 км, T =  1.02 час, V = 43.31 км/ч
