# 3.3 Задача. Операции c матрицами

## Создание двумерного массива

В NumPy существует много способов создать массив. Проще всего создать массив из списка, каждый элемент которого представляет собой новый список. Для этого используется функция array(). На основе списка будет создан массив, количество строк которого будет равно количеству вложенных списков, количество столбцов – количеству элементов в каждом.

In [1]:
import numpy as np

a = np.array([[3, 4, -2], [-2, -1, 4], [1, 2, 1]])
a

array([[ 3,  4, -2],
       [-2, -1,  4],
       [ 1,  2,  1]])

При создании двумерного массива  можно переопределить тип его элементов.

In [2]:
a = np.array([['3', '4', '-2'], ['-2', '-1', '4'], ['1', '2', '1']], dtype=int)
a

array([[ 3,  4, -2],
       [-2, -1,  4],
       [ 1,  2,  1]])

Другой способ - создать на основе данных, введенных пользователем с клавиатуры.
```python
array_list = [ ]

for i in range(3):
    line = input("Введите строку чисел через пробел: ")
    array_str = line.split()
    array_list.append(array_str)

a = np.array(array_list, dtype=int)
```

## Обращение к элементам массива

In [3]:
print('a:\n', a)
print()
print('a[0, 0]:', a[0, 0])
print('a[1, 2]:', a[1, 2])
print('a[2, 1]:', a[2, 1])

a:
 [[ 3  4 -2]
 [-2 -1  4]
 [ 1  2  1]]

a[0, 0]: 3
a[1, 2]: 4
a[2, 1]: 2


### Срезы

Последние значения не включаются.

Срез -- как новый массив.

In [4]:
print('a:\n', a)
print()
print('a[2]:\n', a[2])
print()
print('a[:,1]:\n', a[:,1])
print()
print('a[:2]:\n', a[:2])
print()
print('a[1:3]:\n', a[1:3])
print()
print('a[:,:2]:\n', a[:,:2])
print()
print('a[:,1:3]:\n', a[:,1:3])
print()
print('', )
print('a[0:2, 1:3]:\n', a[0:2, 1:3])
print('', )
print(f'id(a)={id(a)}, id(a[:,:])={id(a[:,:])}')

a:
 [[ 3  4 -2]
 [-2 -1  4]
 [ 1  2  1]]

a[2]:
 [1 2 1]

a[:,1]:
 [ 4 -1  2]

a[:2]:
 [[ 3  4 -2]
 [-2 -1  4]]

a[1:3]:
 [[-2 -1  4]
 [ 1  2  1]]

a[:,:2]:
 [[ 3  4]
 [-2 -1]
 [ 1  2]]

a[:,1:3]:
 [[ 4 -2]
 [-1  4]
 [ 2  1]]


a[0:2, 1:3]:
 [[ 4 -2]
 [-1  4]]

id(a)=101281680, id(a[:,:])=101376720


## Функции срезов

Тут обычно второй аргумент указывает ось, вдоль которой работает функция: `0` – стлобцы, `1` – строки.

* `np.max(a,0)` – Находит максимальные элементы в каждом столбце матрицы **a**, результат – вектор, размерность которого равна количеству столбцов матрицы.
* `np.max(a,1)` – Находит максимальные элементы в каждой строке матрицы **a**, результат – вектор, размерность которого равна количеству строк матрицы.
* `np.min(a,0)` – Находит минимальные элементы в каждом столбце матрицы **a**, результат – вектор, размерность которого равна количеству столбцов матрицы.
* `np.min(a,1)` – Находит минимальные  элементы в каждой строке матрицы **a**, результат – вектор, размерность которого равна количеству строк матрицы.
* `np.mean(a,0)` – Находит среднее значение каждого столбца матрицы **a**, результат – вектор, размерность которого равна количеству столбцов матрицы.
* `np.mean(a,1)` – Находит среднее значение каждой строки матрицы **a**, результат – вектор, размерность которого равна количеству строк матрицы.
* `np.sum(a,0)` – Находит сумму каждого столбца матрицы **a**, результат – вектор, размерность которого равна количеству столбцов матрицы.
* `np.sum(a,1)` – Находит сумму каждой строки матрицы **a**, результат – вектор, размерность которого равна количеству строк матрицы.
* `np.prod(a,0)` –	Находит произведение каждого столбца матрицы **a**, результат – вектор, размерность которого равна количеству столбцов матрицы.
* `np.prod(a,1)` –	Находит произведение каждой строки матрицы **a**, результат – вектор, размерность которого равна количеству строк матрицы.
* `np.diag(a)` – Находит диагональные элементы квадратной матрицы, результат – вектор, размерностью равной количеству строк (или столбцов) матрицы **a**.
* `np.triu(a,i)` – Выделяет треугольную матрицу из матрицы **a**, **i** – целое число, которое означает «сдвиг» стороны (гипотенузы) треугольника относительно главной диагонали, результат – матрица, равна по размеру матрице **a**, элементы, не относящиеся к «треугольнику», заполняются нулями.

In [5]:
a = np.array(np.arange(9))
a = a.reshape(3, 3)

print(a)
print()
print(np.sum(a, 0))
print()
print(np.sum(a, 1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[ 9 12 15]

[ 3 12 21]


## Матричные операции

В модуле линейной алгебры

In [6]:
import numpy.linalg as alg

## Step 5

Выберите верные операторы.


* d = np.dot(c, b)
* det_array = alg.det(c)
* d = 5 * a
* d = alg.inv(c)
* d = 12 - b
* d = np.dot(c, c)

In [7]:
import numpy as np
import numpy.linalg as alg

a = np.array([[3, 4, -2], [-2, -1, 4]])

b = np.array([[1, -3, -2, 1], [2, 4, -2, -1], [5, -2, 0, -2]])

c = np.array([[-1, 0, 2], [2, -2, 3], [0, 5, 1]])

In [8]:
print(f'a:\n{a}')
print(f'b:\n{b}')
print(f'c:\n{c}')

a:
[[ 3  4 -2]
 [-2 -1  4]]
b:
[[ 1 -3 -2  1]
 [ 2  4 -2 -1]
 [ 5 -2  0 -2]]
c:
[[-1  0  2]
 [ 2 -2  3]
 [ 0  5  1]]


In [9]:
d = np.dot(c, b)
d

array([[  9,  -1,   2,  -5],
       [ 13, -20,   0,  -2],
       [ 15,  18, -10,  -7]])

In [10]:
det_array = alg.det(c)
det_array

36.99999999999999

In [11]:
d = 5 * a
d

array([[ 15,  20, -10],
       [-10,  -5,  20]])

In [12]:
d = alg.inv(c)
d

array([[-0.45945946,  0.27027027,  0.10810811],
       [-0.05405405, -0.02702703,  0.18918919],
       [ 0.27027027,  0.13513514,  0.05405405]])

In [13]:
d = 12 - b
d

array([[11, 15, 14, 11],
       [10,  8, 14, 13],
       [ 7, 14, 12, 14]])

In [14]:
d = np.dot(c, c)
d

array([[ 1, 10,  0],
       [-6, 19,  1],
       [10, -5, 16]])

## Step 7

Решить систему линейных уравнений матричным способом.

$$
\begin{equation*}
 \begin{cases}
   -2x_1-8.5x_2-3.4x_3+3.5x_4=-1.88\\
   2.4x_2+8.2x_4=-3.28\\
   2.5x_1-1.6x_2-2.1x_3+3x_4=-0.5\\
   0.3x_1-0.4x_2-4.8x_3+4.6x_4=-2.83
 \end{cases}
\end{equation*}
$$

Для этого:

* сформировать матрицу А, состоящую из коэффициентов левых частей уравнений (должна получиться матрица размером 4 на 4);
* сформировать вектор В, каждый элемент которого - соответствующие значения правых частей уравнений;
* вычислить вектор - решение системы уравнений по формуле:
$$X=A^{-1}\dot B$$

* вывести полученный вектор, округлив значения до одного знака после запятой.

**Входные данные:**
* нет

**Выходные данные:**
* вектор-решение.

Результат при выводе округлить до одного знака после запятой, используя функцию модуля numpy.

___

**Sample Input:**

**Sample Output:**
```
[ 0.1 -0.1  0.2 -0.4]
```

In [15]:
import numpy as np
import numpy.linalg as alg

In [16]:
a = np.array([[-2, -8.5, -3.4, 3.5],
              [0., 2.4, 0., 8.2],
              [2.5, 1.6, 2.1, 3],
              [0.3, -0.4, -4.8, 4.6]])
a

array([[-2. , -8.5, -3.4,  3.5],
       [ 0. ,  2.4,  0. ,  8.2],
       [ 2.5,  1.6,  2.1,  3. ],
       [ 0.3, -0.4, -4.8,  4.6]])

In [17]:
b = np.array([-1.88, -3.28, -0.5, -2.83])
b

array([-1.88, -3.28, -0.5 , -2.83])

In [18]:
x = np.dot(alg.inv(a), b)
x = np.round(x, 1)
x

array([ 0.1, -0.1,  0.2, -0.4])

## Step 11

In [19]:
import numpy as np

b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
print(b[:2, :2])

[[1 2]
 [5 6]]


In [21]:
print(b[2])

[ 9 10 11 12]


In [22]:
print(b[:2])

[[1 2 3 4]
 [5 6 7 8]]


In [23]:
print(b[:2, 2])

[3 7]


In [24]:
print(b[: , 2])

[ 3  7 11]


## Step 13

**Задача.**

Дан многоугольник на плоскости, заданный  координатами своих вершин. Найти координаты вершин многоугольника, полученные поворотом каждой точки  на заданный угол вокруг начала координат. Вычислить средние значения координат по оси ОХ и ОУ повернутого многоугольника.

**Входные данные:**

* количество вершин многоугольника (целое число);
* список вершин многоугольника, каждая вершина на отдельной строке, строка состоит из двух чисел через пробел, определяющие 
* координаты вершины по оси ОХ и OY (целые числа);
* угол поворота в градусах (целое число).

**Выходные данные:**

среднее значение абсцисс (координат x) и ординат(координат y) точек повернутого многоугольника, для вывода использовать шаблон:
```
"avg_x = %6.2f, avg_y = %6.2f"
```

**Пояснение:**

* Создать двухмерный массив из вершин многоугольника (количество строк - количество вершин, количество столбцов  2, для координат x и у точки).
* Умножить массив вершин на матрицу поворота. Полученная матрица - координаты вершин многоугольника после поворота.

$$
\begin{bmatrix}
\cos\phi  & \sin\phi \\
-\sin\phi & \cos\phi
\end{bmatrix}
$$
* Найти среднее значение первого столбца (avg_x) и среднее значение второго (avg_y).

___

**Sample Input:**
```
3
-7 -8
-11 4
-9 5
45
```
**Sample Output:**
```
avg_x =  -6.60, avg_y =  -6.13
```

In [25]:
import numpy as np

In [26]:
# # вводим количество вершин многоугольника
# n_vertices = int(input())

# # вводим координаты вершин
# vertices = []
# for _ in range(n_vertices):
#     v = input()
#     vx, vy = map(int, v.split())
#     vertices.append([vx, vy])

# # вводим угол поворота
# phi = int(input())

In [27]:
input_n_vertices = '3'
input_v1 = '-7 -8'
input_v2 = '-11 4'
input_v3 = '-9 5'
input_phi = '45'

# вводим количество вершин многоугольника
n_vertices = int(input_n_vertices)

# вводим координаты вершин
vertices = []
for v in [input_v1, input_v2, input_v3]:
    vx, vy = map(int, v.split())
    vertices.append([vx, vy])

# вводим угол поворота
phi = int(input_phi)

In [28]:
# матрица координат всех вершин
vertices = np.array(vertices, dtype=int)
vertices

array([[ -7,  -8],
       [-11,   4],
       [ -9,   5]])

In [29]:
# матрица поворота
phi_rad = np.radians(phi)
rotate = np.array([[np.cos(phi_rad), np.sin(phi_rad)],
                   [-np.sin(phi_rad), np.cos(phi_rad)]])

rotate

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [30]:
# поворациваем вершины
rotated_vertice = np.dot(vertices, rotate)
rotated_vertice

array([[  0.70710678, -10.60660172],
       [-10.60660172,  -4.94974747],
       [ -9.89949494,  -2.82842712]])

In [31]:
# ищем центр масс
avg = np.mean(rotated_vertice, 0)

print("avg_x = %6.2f, avg_y = %6.2f" % (avg[0], avg[1]))

avg_x =  -6.60, avg_y =  -6.13
